#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/shercoremoto/shercoremoto /usr/bin/shercoremoto

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/shercoremoto.service ]; then
			rm -f /etc/systemd/system/shercoremoto.service /usr/lib/systemd/system/shercoremoto.service /usr/lib/systemd/user/shercoremoto.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/shercoremoto/files/systemd/shercoremoto.service /usr/lib/systemd/system/shercoremoto.service
		# try fix error in Ubuntu 18.04
		# Failed to reload shercoremoto.service: Unit shercoremoto.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/shercoremoto.service:10: Executable path is not absolute: pkill -f "shercoremoto --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/shercoremoto.service
		fi
		systemctl daemon-reload
		systemctl enable shercoremoto
		systemctl start shercoremoto
	fi
fi
